bump cert-manager version up to 1.17.4
Signed-off-by: suselz <suselz@mail.ru>

diff --git a/modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml b/modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml
--- a/modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml
+++ b/modules/101-cert-manager/images/cert-manager-controller/werf.inc.yaml
@@ -1,8 +1,8 @@
-{{- $version := "1.17.1" }}
+{{- $version := "1.17.4" }}
 image: {{ $.ModuleName }}/{{ $.ImageName }}
 fromImage: common/distroless
 import:
-- image: {{ $.ModuleName }}/{{ $.ImageName }}-artifact-{{ $version | replace "." "-" }}
+- image: {{ $.ModuleName }}/{{ $.ImageName }}-artifact
   add: /controller-linux-amd64
   to: /bin/cert-manager-controller
   before: setup
@@ -10,7 +10,7 @@ imageSpec:
   config:
     entrypoint: ["/bin/cert-manager-controller"]
 ---
-image: {{ $.ModuleName }}/{{ $.ImageName }}-src-artifact
+image: {{ $.ModuleName }}/{{ $.ImageName }}-src-artifact-{{ $version | replace "." "-" }}
 fromImage: common/src-artifact
 final: false
 git:
@@ -19,6 +19,8 @@ git:
   stageDependencies:
     install:
     - '**/*'
+- add: /{{ $.ModulePath }}modules/101-{{ $.ModuleName }}/crds
+  to: /module_crds    
 secrets:
 - id: SOURCE_REPO
   value: {{ .SOURCE_REPO }}
@@ -33,18 +35,54 @@ shell:
   - git show -s --format=%ct HEAD > GITEPOCH
   - rm -rf /src/.git
 ---
-image: {{ $.ModuleName }}/{{ $.ImageName }}-artifact-{{ $version | replace "." "-" }}
+image: {{ $.ModuleName }}/{{ $.ImageName }}-validator
+fromImage: common/src-artifact
+final: false
+git:
+- add: /{{ $.ModulePath }}modules/101-{{ $.ModuleName }}/crds
+  to: /module_crds
+- add: /{{ $.ModulePath }}modules/101-{{ $.ModuleName }}/docs
+  to: /docs  
+import:
+- image: {{ .ModuleName }}/{{ .ImageName }}-src-artifact-{{ $version | replace "." "-" }}
+  add: /src/deploy/crds
+  to: /src/deploy/crds
+  before: install
+- image: tools/yq
+  add: /usr/bin/yq
+  to: /usr/bin/yq
+  before: install
+shell:
+  install:
+  - | 
+    echo "Checking if module crds are the same as cert-manager crds"
+    DOWNLOAD=false CRD_PATH=/src/deploy/crds /module_crds/pull_crds.sh
+
+    dir1="/src/deploy/crds"
+    dir2="/module_crds"
+    for f in $dir1/*.yaml; do
+      base=$(basename "$f")
+        diff -u "$dir1/$base" "$dir2/$base"
+    done  
+
+  - |
+    echo "Checking cert-manager version in documentation"
+    cat /docs/README.md    | grep {{ $version }} || ( echo "ERROR: version v{{ $version }} not found in /docs/README.md"    && exit 1 )
+    cat /docs/README_RU.md | grep {{ $version }} || ( echo "ERROR: version v{{ $version }} not found in /docs/README_RU.md" && exit 1 )
+
+---
+image: {{ $.ModuleName }}/{{ $.ImageName }}-artifact
 fromImage: {{ eq $.SVACE_ENABLED "false" | ternary "builder/golang-bookworm" "builder/golang-bookworm-svace" }}
 final: false
 import:
-- image: {{ .ModuleName }}/{{ .ImageName }}-src-artifact
+- image: {{ .ModuleName }}/{{ .ImageName }}-src-artifact-{{ $version | replace "." "-" }}
   add: /src
   to: /src
   before: install
 - image: tools/jq
   add: /usr/bin/jq
   to: /usr/bin/jq
-  before: install
+  before: install  
 mount:
 {{ include "mount points for golang builds" . }}
 secrets:
