[ci] backport: fix: detect version to suspend #1124

diff --git a/.github/workflow_templates/suspend-channel.multi.yml b/.github/workflow_templates/suspend-channel.multi.yml
--- a/.github/workflow_templates/suspend-channel.multi.yml
+++ b/.github/workflow_templates/suspend-channel.multi.yml
@@ -1,3 +1,13 @@
+{!{/*
+  Multifile generator of suspend workflows.
+
+  One workflow file for each channel: suspend-alpha.yml, suspend-beta.yml, etc.
+
+  The only reason to use separate files for each channel
+  is a filtering on 'Actions' page.
+
+*/}!}
+
 {!{- range $channel := slice "alpha" "beta" "early-access" "stable" "rock-solid" -}!}
 {!{- $ctx := dict "channel" $channel }!}
 {!{- $outFile := printf "suspend-%s.yml" $channel }!}
@@ -15,45 +25,68 @@ on:
     inputs:
       issue_id:
         description: 'Id of issue where label was set'
-        required: true
+        required: false
       issue_number:
         description: 'Number of issue where label was set'
-        required: true
+        required: false
       comment_id:
         description: 'Id of comment in issue where to put workflow run status'
-        required: true
+        required: false
+      suspend_tag:
+        description: 'Set to suspend specified tag'
+        required: false
 
 env:
 {!{ tmpl.Exec "werf_envs" | strings.Indent 2 }!}
   DEPLOY_CHANNEL: {!{ .channel }!}
 
-# Analog of Gitlab's "interruptible: true" behaviour.
-# Note: Concurrency is currently in beta and subject to change.
-# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
-concurrency:
-  group: ${{ github.ref }}-suspend-channel-{!{ .channel }!}
-  cancel-in-progress: true
+# Note: no concurrency section for suspend workflows.
 
 jobs:
 {!{ tmpl.Exec "git_info_job" . | strings.Indent 2 }!}
 
-{!{ tmpl.Exec "check_label_job" (slice "suspend" .channel) | strings.Indent 2 }!}
+  detect_version:
+    name: Detect version
+    needs:
+      - git_info
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{steps.detect_version.outputs.version}}
+    steps:
+      - name: Detect version
+        id: detect_version
+        env:
+          CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+          CI_COMMIT_REF_NAME: ${{needs.git_info.outputs.ci_commit_ref_name}}
+          SUSPEND_TAG: ${{ github.event.inputs.suspend_tag }}
+        run: |
+          if [[ -n ${SUSPEND_TAG} ]] ; then
+            echo "::notice title=Suspend version::Workflow started from '${CI_COMMIT_REF_NAME}', but suspend_tag input is set. Use '${SUSPEND_REVISION}' as suspend version."
+            echo "::set-output name=version::${SUSPEND_TAG}"
+            exit 0
+          fi
+          if [[ -n ${CI_COMMIT_TAG} ]] ; then
+            echo "::notice title=Suspend version::Workflow started from tag '${CI_COMMIT_TAG}'. Use it as suspend version."
+            echo "::set-output name=version::${CI_COMMIT_TAG}"
+            exit 0
+          fi
+
+          echo "::error title=Wrong environment::Seems you try to suspend branch '${CI_COMMIT_REF_NAME}'. Use suspend_tag input or run workflow from tag."
+          exit 1
+
 
   run_suspend:
-    name: Suspend deckhouse release on {!{ .channel }!} channel
+    name: Suspend ${{needs.detect_version.outputs.version}} on {!{ .channel }!} channel
     environment:
       name: {!{ .channel }!}
     needs:
-      - check_label
       - git_info
-    if: needs.check_label.outputs.should_run == 'true'
-    runs-on: self-hosted
+      - detect_version
+    runs-on: [self-hosted, regular]
     steps:
 {!{ tmpl.Exec "checkout_from_event_ref_step" . | strings.Indent 6 }!}
 {!{ tmpl.Exec "update_comment_on_start" $workflowName | strings.Indent 6 }!}
-{!{ tmpl.Exec "restore_images_tags_json_from_cache_or_fail" . | strings.Indent 6 }!}
 {!{ tmpl.Exec "login_dev_registry_step" . | strings.Indent 6 }!}
-{!{ tmpl.Exec "login_readonly_registry_step" . | strings.Indent 6 }!}
 {!{ tmpl.Exec "login_rw_registry_step" . | strings.Indent 6 }!}
 
 {!{/*
@@ -68,47 +101,83 @@ Destination registries:
       - name: Publish release images for {!{ $werfEnv }!}
         env:
           DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
-          CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+          SUSPEND_VERSION: ${{needs.detect_version.outputs.version}}
           WERF_ENV: {!{ $werfEnv }!}
+          SKIP_PUSH_FOR_SUSPEND: ${{secrets.SKIP_PUSH_FOR_SUSPEND}}
         run: |
+          # SRC_NAME is a name of image from werf.yaml.
+          # SRC is a source image name.
+          # DST is an image name for docker push.
+          function push_rmi() {
+            SRC_NAME=$1
+            DST=$2
+
+            enable_push="true"
+            if [[ ${GITHUB_REPOSITORY} != "deckhouse/deckhouse" ]]; then
+              if [[ ${SKIP_PUSH_FOR_SUSPEND} == "true" ]]; then
+                enable_push="false"
+                echo "⚓️ ❎ [$(date -u)] SKIP_PUSH_FOR_SUSPEND=true, skip running 'docker image push ${DST}'."
+              fi
+            fi
+
+            if [[ ${enable_push} == "true" ]] ; then
+              echo "⚓️ 📤 [$(date -u)] Push '${SRC_NAME}' image as ${DST}."
+              docker image push ${DST}
+            fi
+
+            echo "⚓️ 🧹 [$(date -u)] Remove local tag for '${SRC_NAME}'."
+            docker image rmi ${DST} || true;
+          }
+
           # Some precautions.
-          if [[ -z $DEV_REGISTRY_PATH ]] ; then
-            echo "DEV_REGISTRY_PATH is not set!"
+          shouldExit1=
+          if [[ -z ${DEV_REGISTRY_PATH} ]] ; then
+            echo "::error title=Missed variable::DEV_REGISTRY_PATH is not set. Define destination registry in secrets."
+            shouldExit1=yes
+          fi
+          if [[ -z ${WERF_ENV} ]] ; then
+            echo "::error title=Missed variable::WERF_ENV is not set. Cannot deploy unknown edition, only ce, ee and fe are allowed in inputs."
+            shouldExit1=yes
+          fi
+          if [[ -z ${SUSPEND_VERSION} ]] ; then
+            echo "::error title=Missed version::Suspend version not detected. Use suspend_tag input or run workflow from tag."
+            shouldExit1=yes
+          fi
+          if [[ -n ${shouldExit1} ]] ; then
             exit 1
           fi
-          if [[ -z $WERF_ENV ]] ; then
-            echo "WERF_ENV is not set!"
-            exit 1
-          fi
+
+          echo "Suspend version '${SUSPEND_VERSION}' for {!{ $werfEnv }!} edition".
 
           # Variables
-          #   1. CE/EE/FE -> ce/ee/fe
+          #   1. Edition and channel.
+          # CE/EE/FE -> ce/ee/fe
           REGISTRY_SUFFIX=$(echo ${WERF_ENV} | tr '[:upper:]' '[:lower:]')
-          echo "Registry suffix - ${REGISTRY_SUFFIX}"
-
-          #   2. alpha: [EE] -> alpha , beta: [CE] -> beta
           RELEASE_CHANNEL={!{ $channel }!}
-          echo "Release channel - ${RELEASE_CHANNEL}"
 
-          #   3. Publish prod images to rw registry
-          if [[ -n "${DECKHOUSE_REGISTRY_HOST}" ]]; then
-            DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE=${DECKHOUSE_REGISTRY_HOST}/deckhouse/${REGISTRY_SUFFIX}/release-channel:${RELEASE_CHANNEL};
-          else
-            DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE=${CI_REGISTRY_IMAGE}/deckhouse/${REGISTRY_SUFFIX}/release-channel:${RELEASE_CHANNEL};
+          echo "⚓️ 💫 [$(date -u)] Start publishing 'release-channel suspend' image for '${REGISTRY_SUFFIX}' edition onto '${RELEASE_CHANNEL}' release channel."
+
+          #   2. Prod registry: use github packages if DECKHOUSE_REGISTRY_HOST not set (run in the test repo).
+          DST_REGISTRY_PATH=${DECKHOUSE_REGISTRY_HOST}/deckhouse
+          if [[ -z "${DECKHOUSE_REGISTRY_HOST}" ]]; then
+            DST_REGISTRY_PATH="${GHA_TEST_REGISTRY_PATH}"
+            echo "⚓️ 🧪 [$(date -u)] DECKHOUSE_REGISTRY_HOST is empty. Publish to Github Container Registry '${DST_REGISTRY_PATH}'"
           fi
 
-          echo "{\"version\": \"$CI_COMMIT_REF_NAME\", \"suspend\": true}" > version.json
+          #   3. Build and publish release-channel image to prod registry.
+          SUSPEND_VERSION_IMAGE=${DST_REGISTRY_PATH}/${REGISTRY_SUFFIX}/release-channel:${RELEASE_CHANNEL}
+          echo "⚓️ 🛠 [$(date -u)] Build 'release-channel suspend' image as '${SUSPEND_VERSION_IMAGE}'."
+
+          echo "{\"version\": \"${SUSPEND_VERSION}\", \"suspend\": true}" > version.json
           cat <<EOF >Dockerfile
           FROM spotify/scratch
           COPY version.json version.json
           EOF
-          docker build . -t $DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE
+          docker build . -t "${SUSPEND_VERSION_IMAGE}"
 
-          docker image push ${DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE}
-          echo "Delete local 'release version' image ${DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE}"
-          docker image rmi ${DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE} || true
+          push_rmi 'release-channel suspend' "${SUSPEND_VERSION_IMAGE}"
 
-          echo "Release version image: ${DECKHOUSE_DESTINATION_RELEASE_VERSION_IMAGE}"
+
 {!{- end }!}
 
 {!{ tmpl.Exec "update_comment_on_finish" (slice "job" $workflowName) | strings.Indent 6 }!}
