[secret-copier] Secret deletion from not existing namespace fix

diff --git a/modules/600-secret-copier/hooks/delete_secret b/modules/600-secret-copier/hooks/delete_secret
--- a/modules/600-secret-copier/hooks/delete_secret
+++ b/modules/600-secret-copier/hooks/delete_secret
@@ -37,7 +37,7 @@ function __main__() {
         continue
       fi
 
-      kubectl -n $namespace delete secret $secret
+      kubectl -n $namespace delete secret $secret || echo "Deletion of secret $secret in namespace $namespace failed. Skipping... "
     done
   done
 }
