2025-08-12 14:16:10.471796373 +0300 MSK m=+3.707059238

diff --git a/modules/500-dashboard/enabled b/modules/500-dashboard/enabled
--- a/modules/500-dashboard/enabled
+++ b/modules/500-dashboard/enabled
@@ -19,21 +19,38 @@ source /deckhouse/shell_lib.sh
 function __main__() {
   enabled::disable_module_if_cluster_is_not_bootstraped
 
-  echo "false" > $MODULE_ENABLED_RESULT
-  if values::has global.modules.publicDomainTemplate ; then
-    https_mode=$(values::get_first_defined dashboard.https.mode global.modules.https.mode)
-    if [ "$https_mode" != "Disabled" ] ; then
-      if values::array_has global.enabledModules "user-authz" ; then
-        if ! values::array_has global.enabledModules "user-authn"; then
-          if values::has dashboard.auth.externalAuthentication.authSignInURL && values::has dashboard.auth.externalAuthentication.authURL; then
-            echo "true" > $MODULE_ENABLED_RESULT
-          fi
-        else
-          echo "true" > $MODULE_ENABLED_RESULT
-        fi
-      fi
-    fi
+  if ! values::has global.modules.publicDomainTemplate ; then
+    echo "false" > "$MODULE_ENABLED_RESULT"
+    echo "spec.settings.modules.publicDomainTemplate is not set in the global configuration, configure it in ModuleConfig/global." > "$MODULE_ENABLED_REASON"
+    return
+  fi
+
+  https_mode=$(values::get_first_defined dashboard.https.mode global.modules.https.mode)
+  if [ "$https_mode" = "Disabled" ]; then
+    echo "false" > "$MODULE_ENABLED_RESULT"
+    echo "https.mode is set to 'Disabled' - set it in ModuleConfig/global or ModuleConfig/dashboard." > "$MODULE_ENABLED_REASON"
+    return
+  fi
+
+  if ! values::array_has global.enabledModules "user-authz" ; then
+    echo "false" > "$MODULE_ENABLED_RESULT"
+    echo "'user-authz' module needs to be enabled." > "$MODULE_ENABLED_REASON"
+    return
+  fi
+
+  if values::array_has global.enabledModules "user-authn" ; then
+    echo "true" > "$MODULE_ENABLED_RESULT"
+    return
+  fi
+
+  if values::has dashboard.auth.externalAuthentication.authSignInURL && \
+     values::has dashboard.auth.externalAuthentication.authURL ; then
+    echo "true" > "$MODULE_ENABLED_RESULT"
+  else
+    echo "false" > "$MODULE_ENABLED_RESULT"
+    echo "required values settings.auth.externalAuthentication.authSignInURL and settings auth.externalAuthentication.authURL - set it in ModuleConfig/dashboard. " > "$MODULE_ENABLED_REASON"
   fi
 }
 
-enabled::run $@
+
+enabled::run "$@"
