[istio] Fix DexAuthenticator domain
(cherry picked from commit 5b1b88703030a7d3db97edc8a1ef84aac88341da)

diff --git a/modules/110-istio/hooks/remote_clusters_discovery_public_metadata b/modules/110-istio/hooks/remote_clusters_discovery_public_metadata
--- a/modules/110-istio/hooks/remote_clusters_discovery_public_metadata
+++ b/modules/110-istio/hooks/remote_clusters_discovery_public_metadata
@@ -15,8 +15,7 @@ function __config__() {
       jqFilter: |
         {
           "name": .metadata.name,
-          "rootCAEndpoint": ((.spec.metadataEndpoint | sub("/*$"; "")) + "/public/root-cert.pem"),
-          "rootCA": .status.metadataCache.rootCA,
+          "publicEndpoint": ((.spec.metadataEndpoint | sub("/*$"; "")) + "/public/public.json"),
           "trustDomain": .spec.trustDomain
         }
     - name: multiclusters
@@ -28,8 +27,7 @@ function __config__() {
       jqFilter: |
         {
           "name": .metadata.name,
-          "rootCAEndpoint": ((.spec.metadataEndpoint | sub("/*$"; "")) + "/public/root-cert.pem"),
-          "rootCA": .status.metadataCache.rootCA
+          "publicEndpoint": ((.spec.metadataEndpoint | sub("/*$"; "")) + "/public/public.json")
         }
     schedule:
     - name: remote
@@ -45,28 +43,23 @@ function __main__() {
       federationSpec="$(context::jq --argjson i "$i" -c '.snapshots.federations[$i] | .filterResult')"
       federationName="$(jq -r '.name'           <<< "$federationSpec")"
       trustDomain="$(jq    -r '.trustDomain'    <<< "$federationSpec")"
-      rootCAEndpoint="$(jq -r '.rootCAEndpoint' <<< "$federationSpec")"
-      rootCACache="$(jq    -r '.rootCA'         <<< "$federationSpec")"
+      publicEndpoint="$(jq -r '.publicEndpoint' <<< "$federationSpec")"
 
       if [[ "$trustDomain" == "$(values::get global.discovery.clusterDomain)" ]]; then continue; fi
 
       isError=0
-      # try to fetch pem from endpoint
-      if rootCA="$(curl -f -s --show-error "$rootCAEndpoint")"; then
-        if [[ "$rootCA" != "$rootCACache" ]]; then
-          patch="$(jq -n --arg rca "$rootCA" '{"metadataCache":{"rootCA": $rca, "rootCALastFetchTimestamp": (now | todateiso8601)}}')"
-        else
-          patch="$(jq -n '{"metadataCache":{"rootCALastFetchTimestamp": (now | todateiso8601)}}')"
-        fi
+      # try to fetch endpoint
+      if public="$(curl -f -s -m 3 --show-error "$publicEndpoint" | jq -e .)"; then
+        patch="$(jq -n --argjson p "$public" '{"metadataCache":{"public": $p, "publicLastFetchTimestamp": (now | todateiso8601)}}')"
         kubernetes::status::merge_patch "" "deckhouse.io/v1alpha1" "istiofederations" "$federationName" "$patch"
       else
         isError=1
-        echo >&2 "ERROR: Cannot fetch root CA endpoint $rootCAEndpoint for IstioFederation $federationName."
+        echo >&2 "ERROR: Cannot fetch public metadata endpoint $publicEndpoint for IstioFederation $federationName."
       fi
 
-      jq -n --argjson isError "$isError" --arg federationName "$federationName" --arg endpoint "$rootCAEndpoint" '
+      jq -n --argjson isError "$isError" --arg federationName "$federationName" --arg endpoint "$publicEndpoint" '
         {
-          "group":"federation_fetch_rootca",
+          "group":"federation_fetch_public",
           "name": "d8_istio_federation_metadata_endpoints_fetch_error_count",
           "set": $isError,
           "labels": {"federation_name": $federationName, "endpoint": $endpoint}
@@ -79,26 +72,21 @@ function __main__() {
     for i in $(context::jq -r '.snapshots.multiclusters | keys[]'); do
       multiclusterSpec="$(context::jq --argjson i "$i" -c '.snapshots.multiclusters[$i] | .filterResult')"
       multiclusterName="$(jq -r '.name'           <<< "$multiclusterSpec")"
-      rootCAEndpoint="$(jq   -r '.rootCAEndpoint' <<< "$multiclusterSpec")"
-      rootCACache="$(jq      -r '.rootCA'         <<< "$multiclusterSpec")"
+      publicEndpoint="$(jq   -r '.publicEndpoint' <<< "$multiclusterSpec")"
 
       isError=0
-      # try to fetch pem from endpoint
-      if rootCA="$(curl -f -s --show-error "$rootCAEndpoint")"; then
-        if [[ "$rootCA" != "$rootCACache" ]]; then
-          patch="$(jq -n --arg rca "$rootCA" '{"metadataCache":{"rootCA": $rca, "rootCALastFetchTimestamp": (now | todateiso8601)}}')"
-        else
-          patch="$(jq -n '{"metadataCache":{"rootCALastFetchTimestamp": (now | todateiso8601)}}')"
-        fi
+      # try to fetch endpoint
+      if public="$(curl -f -s -m 3 --show-error "$publicEndpoint" | jq -e .)"; then
+        patch="$(jq -n --argjson p "$public" '{"metadataCache":{"public": $p, "publicLastFetchTimestamp": (now | todateiso8601)}}')"
         kubernetes::status::merge_patch "" "deckhouse.io/v1alpha1" "istiomulticlusters" "$multiclusterName" "$patch"
       else
         isError=1
-        echo >&2 "ERROR: Cannot fetch root CA endpoint $rootCAEndpoint for IstioMulticluster $multiclusterName."
+        echo >&2 "ERROR: Cannot fetch public metadata endpoint $publicEndpoint for IstioMulticluster $multiclusterName."
       fi
 
-      jq -n --argjson isError "$isError" --arg multiclusterName "$multiclusterName" --arg endpoint "$rootCAEndpoint" '
+      jq -n --argjson isError "$isError" --arg multiclusterName "$multiclusterName" --arg endpoint "$publicEndpoint" '
         {
-          "group":"multicluster_fetch_rootca",
+          "group":"multicluster_fetch_public",
           "name": "d8_istio_multicluster_metadata_endpoints_fetch_error_count",
           "set": $isError,
           "labels": {"multicluster_name": $multiclusterName, "endpoint": $endpoint}
