++ render

diff --git a/.github/workflows/deploy-alpha.yml b/.github/workflows/deploy-alpha.yml
--- a/.github/workflows/deploy-alpha.yml
+++ b/.github/workflows/deploy-alpha.yml
@@ -117,12 +117,75 @@ jobs:
 
   # </template: git_info_job>
 
+  detect_editions:
+    name: Detect editions
+    runs-on: ubuntu-latest
+    outputs:
+      DEPLOY_CE: ${{steps.detect_editions.outputs.DEPLOY_CE}}
+      DEPLOY_EE: ${{steps.detect_editions.outputs.DEPLOY_EE}}
+      DEPLOY_FE: ${{steps.detect_editions.outputs.DEPLOY_FE}}
+    steps:
+      - name: Detect editions
+        id: detect_editions
+        env:
+          EDITIONS: ${{ github.event.inputs.editions }}
+        run: |
+          echo "Input allowed editions: '${EDITIONS}'"
+
+          RESTRICTED=no
+
+          for edition in CE EE FE ; do
+            if grep -i ",${edition}," <<<",${EDITIONS}," 2>/dev/null 1>&2 ; then
+              echo "  - enable deploy of ${edition} edition."
+              echo "::set-output name=DEPLOY_${edition}::true"
+              RESTRICTED=yes
+            fi
+          done
+
+          if [[ $RESTRICTED == "no" ]] ; then
+            echo "No restrictions. Enable deploy to all editions."
+            for edition in CE EE FE ; do
+              echo "::set-output name=DEPLOY_${edition}::true"
+            done
+          fi
+
+
+
+  enable_CE:
+    if: ${{ needs.detect_editions.outputs.DEPLOY_CE == 'true' }}
+    name: Enable CE
+    needs:
+      - detect_editions
+    runs-on: ubuntu-latest
+    steps:
+      - run: ": Enable CE"
+
+  enable_EE:
+    if: ${{ needs.detect_editions.outputs.DEPLOY_EE == 'true' }}
+    name: Enable EE
+    needs:
+      - detect_editions
+    runs-on: ubuntu-latest
+    steps:
+      - run: ": Enable EE"
+
+  enable_FE:
+    if: ${{ needs.detect_editions.outputs.DEPLOY_FE == 'true' }}
+    name: Enable FE
+    needs:
+      - detect_editions
+    runs-on: ubuntu-latest
+    steps:
+      - run: ": Enable FE"
+
+
   run_deploy:
-    name: Deploy deckhouse to alpha channel
+    name: Deploy ${{needs.git_info.outputs.ci_commit_tag}} to alpha
     environment:
       name: alpha
     needs:
       - git_info
+      - detect_editions
     runs-on: [self-hosted, regular]
     steps:
 
@@ -172,6 +235,23 @@ jobs:
           logout: false
       # </template: login_dev_registry_step>
 
+      # <template: login_readonly_registry_step>
+      - name: Check readonly registry credentials
+        id: check_readonly_registry
+        env:
+          HOST: ${{secrets.DECKHOUSE_REGISTRY_READ_HOST}}
+        run: |
+          if [[ -n $HOST ]]; then echo "::set-output name=has_credentials::true"; fi
+      - name: Login to readonly registry
+        uses: docker/login-action@v1.10.0
+        if: ${{ steps.check_readonly_registry.outputs.has_credentials == 'true' }}
+        with:
+          registry: ${{ secrets.DECKHOUSE_REGISTRY_READ_HOST }}
+          username: ${{ secrets.DECKHOUSE_REGISTRY_READ_USER }}
+          password: ${{ secrets.DECKHOUSE_REGISTRY_READ_PASSWORD }}
+          logout: false
+      # </template: login_readonly_registry_step>
+
       # <template: login_rw_registry_step>
       - name: Check rw registry credentials
         id: check_rw_registry
@@ -197,37 +277,27 @@ jobs:
           logout: false
       # </template: login_rw_registry_step>
 
-      - name: Filter editions
-        id: filter_editions
+      - name: Check push enabled
+        id: check_push
         env:
-          EDITIONS: ${{ github.event.inputs.editions }}
+          SKIP_PUSH_FOR_DEPLOY: ${{secrets.SKIP_PUSH_FOR_DEPLOY}}
+          REPO: ${{github.repository}}
         run: |
-          echo "Input allowed editions: '${EDITIONS}'"
-
-          RESTRICTED=no
-
-          for edition in CE EE FE ; do
-            if grep -i ",${edition}," <<<",${EDITIONS}," 2>/dev/null 1>&2 ; then
-              echo "  - enable deploy of ${edition} edition."
-              echo "::set-output name=DEPLOY_${edition}::yes"
-              RESTRICTED=yes
-            fi
-          done
-
-          if [[ $RESTRICTED == "no" ]] ; then
-            echo "No restrictions. Enable deploy to all editions."
-            for edition in CE EE FE ; do
-              echo "::set-output name=DEPLOY_${edition}::yes"
-            done
+          if [[ ${REPO} == "deckhouse/deckhouse" ]]; then
+            echo "::set-output name=enable::true"
+          fi
+          if [[ ${SKIP_PUSH_FOR_DEPLOY} != "true" ]]; then
+            echo "::set-output name=enable::true"
           fi
 
 
 
       - name: Publish release images for CE
-        if: ${{ steps.filter_editions.outputs.DEPLOY_CE == 'yes' }}
+        if: ${{ needs.detect_editions.outputs.DEPLOY_CE == 'true' }}
         env:
           DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
           CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+          CI_COMMIT_BRANCH: ${{needs.git_info.outputs.ci_commit_branch}}
           WERF_ENV: CE
           SKIP_PUSH_FOR_DEPLOY: ${{secrets.SKIP_PUSH_FOR_DEPLOY}}
         run: |
@@ -263,14 +333,24 @@ jobs:
           }
 
           # Some precautions.
+          shouldExit1=
           if [[ -z ${DEV_REGISTRY_PATH} ]] ; then
-            echo "DEV_REGISTRY_PATH is not set!"
-            exit 1
+            echo "::error title=Missed variable::DEV_REGISTRY_PATH is not set. Define destination registry in secrets."
+            shouldExit1=yes
           fi
           if [[ -z ${WERF_ENV} ]] ; then
-            echo "WERF_ENV is not set!"
+            echo "::error title=Missed variable::WERF_ENV is not set. Cannot deploy unknown edition, only ce, ee and fe are allowed in inputs."
+            shouldExit1=yes
+          fi
+          if [[ -z ${CI_COMMIT_TAG} ]] ; then
+            echo "::error title=Missed variable::CI_COMMIT_TAG is not set. Probably you try to manually deploy from branch '${CI_COMMIT_BRANCH}'? Deploy allowed for tags only."
+            shouldExit1=yes
+          fi
+          if [[ -n ${shouldExit1} ]] ; then
             exit 1
           fi
+
+          echo "Publish CE edition".
 
           # Variables
           #   1. Edition and channel.
@@ -342,10 +422,11 @@ jobs:
           echo "  Source: ${SOURCE_RELEASE_VERSION_IMAGE}"
           echo "  Prod: ${PROD_RELEASE_VERSION_IMAGE}"
       - name: Publish release images for EE
-        if: ${{ steps.filter_editions.outputs.DEPLOY_EE == 'yes' }}
+        if: ${{ needs.detect_editions.outputs.DEPLOY_EE == 'true' }}
         env:
           DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
           CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+          CI_COMMIT_BRANCH: ${{needs.git_info.outputs.ci_commit_branch}}
           WERF_ENV: EE
           SKIP_PUSH_FOR_DEPLOY: ${{secrets.SKIP_PUSH_FOR_DEPLOY}}
         run: |
@@ -381,14 +462,24 @@ jobs:
           }
 
           # Some precautions.
+          shouldExit1=
           if [[ -z ${DEV_REGISTRY_PATH} ]] ; then
-            echo "DEV_REGISTRY_PATH is not set!"
-            exit 1
+            echo "::error title=Missed variable::DEV_REGISTRY_PATH is not set. Define destination registry in secrets."
+            shouldExit1=yes
           fi
           if [[ -z ${WERF_ENV} ]] ; then
-            echo "WERF_ENV is not set!"
+            echo "::error title=Missed variable::WERF_ENV is not set. Cannot deploy unknown edition, only ce, ee and fe are allowed in inputs."
+            shouldExit1=yes
+          fi
+          if [[ -z ${CI_COMMIT_TAG} ]] ; then
+            echo "::error title=Missed variable::CI_COMMIT_TAG is not set. Probably you try to manually deploy from branch '${CI_COMMIT_BRANCH}'? Deploy allowed for tags only."
+            shouldExit1=yes
+          fi
+          if [[ -n ${shouldExit1} ]] ; then
             exit 1
           fi
+
+          echo "Publish EE edition".
 
           # Variables
           #   1. Edition and channel.
@@ -460,10 +551,11 @@ jobs:
           echo "  Source: ${SOURCE_RELEASE_VERSION_IMAGE}"
           echo "  Prod: ${PROD_RELEASE_VERSION_IMAGE}"
       - name: Publish release images for FE
-        if: ${{ steps.filter_editions.outputs.DEPLOY_FE == 'yes' }}
+        if: ${{ needs.detect_editions.outputs.DEPLOY_FE == 'true' }}
         env:
           DECKHOUSE_REGISTRY_HOST: ${{secrets.DECKHOUSE_REGISTRY_HOST}}
           CI_COMMIT_TAG: ${{needs.git_info.outputs.ci_commit_tag}}
+          CI_COMMIT_BRANCH: ${{needs.git_info.outputs.ci_commit_branch}}
           WERF_ENV: FE
           SKIP_PUSH_FOR_DEPLOY: ${{secrets.SKIP_PUSH_FOR_DEPLOY}}
         run: |
@@ -499,14 +591,24 @@ jobs:
           }
 
           # Some precautions.
+          shouldExit1=
           if [[ -z ${DEV_REGISTRY_PATH} ]] ; then
-            echo "DEV_REGISTRY_PATH is not set!"
-            exit 1
+            echo "::error title=Missed variable::DEV_REGISTRY_PATH is not set. Define destination registry in secrets."
+            shouldExit1=yes
           fi
           if [[ -z ${WERF_ENV} ]] ; then
-            echo "WERF_ENV is not set!"
+            echo "::error title=Missed variable::WERF_ENV is not set. Cannot deploy unknown edition, only ce, ee and fe are allowed in inputs."
+            shouldExit1=yes
+          fi
+          if [[ -z ${CI_COMMIT_TAG} ]] ; then
+            echo "::error title=Missed variable::CI_COMMIT_TAG is not set. Probably you try to manually deploy from branch '${CI_COMMIT_BRANCH}'? Deploy allowed for tags only."
+            shouldExit1=yes
+          fi
+          if [[ -n ${shouldExit1} ]] ; then
             exit 1
           fi
+
+          echo "Publish FE edition".
 
           # Variables
           #   1. Edition and channel.
