[CI] Check format & valid datetime on cooldown release
Signed-off-by: Kirill Kramorov <kirill.kramorov@flant.com>

diff --git a/.github/workflows/deploy-beta.yml b/.github/workflows/deploy-beta.yml
--- a/.github/workflows/deploy-beta.yml
+++ b/.github/workflows/deploy-beta.yml
@@ -341,6 +341,17 @@ jobs:
         run: |
           CURRENT_TIMESTAMP=$(date +%s)
           COOLDOWN_TIMESTAMP=$(date -u +%s -d "${COOLDOWN}")
+          # Check datetime format
+          if ! [[ "$COOLDOWN" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{2}:[0-9]{2}$ ]]; then
+            echo "Invalid datetime format."
+            exit 1
+          fi
+          # Check datetime is valid
+          if ! date -d "$COOLDOWN" >/dev/null 2>&1; then
+            echo "Invalid datetime."
+            exit 1
+          fi
+          # Check datetime is expired
           if [ "$CURRENT_TIMESTAMP" -gt "$COOLDOWN_TIMESTAMP" ]; then
             echo "The cooldown has expired"
             exit 1
