[global] Errors to stderr

diff --git a/modules/040-control-plane-manager/hooks/reconcile_etcd_members b/modules/040-control-plane-manager/hooks/reconcile_etcd_members
--- a/modules/040-control-plane-manager/hooks/reconcile_etcd_members
+++ b/modules/040-control-plane-manager/hooks/reconcile_etcd_members
@@ -67,12 +67,12 @@ function set_etcdctl_credentials() {
   ETCDCTL_ENDPOINTS="$1"
 
   if [[ -z "$ETCDCTL_ENDPOINTS" ]]; then
-    echo "ERROR: Failed to find etcdctl endpoints"
+    >&2 echo "ERROR: Failed to find etcdctl endpoints"
     exit 1
   fi
 
   if [[ ! -s "$ETCDCTL_CERT" || ! -s "$ETCDCTL_KEY" || ! -s "$ETCDCTL_CACERT" ]]; then
-    echo "etcd certs not present in a snapshot storage"
+    >&2 echo "etcd certs not present in a snapshot storage"
     exit 1
   fi
 
diff --git a/modules/450-network-gateway/hooks/check_values b/modules/450-network-gateway/hooks/check_values
--- a/modules/450-network-gateway/hooks/check_values
+++ b/modules/450-network-gateway/hooks/check_values
@@ -11,23 +11,23 @@ EOF
 
 function __main__() {
   if ! values::has networkGateway.nodeSelector; then
-    echo "ERROR: networkGateway.nodeSelector is mandatory."
+    >&2 echo "ERROR: networkGateway.nodeSelector is mandatory."
     return 1
   fi
 
   if ! values::has networkGateway.subnet; then
-    echo "ERROR: networkGateway.subnet is mandatory."
+    >&2 echo "ERROR: networkGateway.subnet is mandatory."
     return 1
   fi
 
   subnet=$(values::get networkGateway.subnet)
   if ! echo "${subnet}" | grep -q -E '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'; then
-    echo "ERROR: networkGateway.subnet format is 'IP/Prefix'."
+    >&2 echo "ERROR: networkGateway.subnet format is 'IP/Prefix'."
     return 1
-  fi 
+  fi
 
   if ! values::has networkGateway.publicAddress; then
-    echo "ERROR: networkGateway.publicAddress is mandatory."
+    >&2 echo "ERROR: networkGateway.publicAddress is mandatory."
     return 1
   fi
 }
